"""Initial migration

Revision ID: 01d0fbd20b25
Revises: 
Create Date: 2026-08-12 18:32:32.451625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01d0fbd20b25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('registered_by_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'serious', 'stable', name='emergency_case_severity'), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'in_progress', 'resolved', 'cancelled', name='emergency_case_status'), nullable=False),
    sa.Column('decision', sa.Enum('ot_surgery', 'icu', 'observation', 'discharge', 'other', name='emergency_case_decision'), nullable=True),
    sa.Column('arrived_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.Column('treatment_notes', sa.Text(), nullable=True),
    sa.Column('linked_appointment_id', sa.Integer(), nullable=True),
    sa.Column('linked_consultation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['linked_appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['linked_consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_cases', schema=None) as batch_op:
        batch_op.create_index('idx_emergency_cases_status_severity', ['status', 'severity'], unique=False)

    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_registration_email'))
        batch_op.drop_index(batch_op.f('idx_registration_status_created'))

    op.drop_table('registration_requests')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.ENUM('appointment', 'consultation', 'report', 'nursing', 'system', 'pharmacy', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('appointment', 'consultation', 'report', 'nursing', 'patient_assignment', 'pharmacy', 'shift', 'system', name='notification_category'),
               existing_nullable=False,
               existing_server_default=sa.text("'system'"))

    with op.batch_alter_table('nursing_assignments', schema=None) as batch_op:
        batch_op.alter_column('care_type',
               existing_type=mysql.ENUM('observation', 'post_surgery', 'post_procedure', 'recovery', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('observation', 'post_surgery', 'post_procedure', 'recovery', 'icu', name='nursing_care_type'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nursing_assignments', schema=None) as batch_op:
        batch_op.alter_column('care_type',
               existing_type=sa.Enum('observation', 'post_surgery', 'post_procedure', 'recovery', 'icu', name='nursing_care_type'),
               type_=mysql.ENUM('observation', 'post_surgery', 'post_procedure', 'recovery', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('appointment', 'consultation', 'report', 'nursing', 'patient_assignment', 'pharmacy', 'shift', 'system', name='notification_category'),
               type_=mysql.ENUM('appointment', 'consultation', 'report', 'nursing', 'system', 'pharmacy', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'system'"))

    op.create_table('registration_requests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('requested_role', mysql.ENUM('doctor', 'nurse', 'receptionist', 'pharmacist'), nullable=False),
    sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('license_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60), nullable=True),
    sa.Column('specialization', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('note', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'approved', 'rejected'), nullable=False),
    sa.Column('reviewed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('review_note', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('created_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('registration_requests_ibfk_1')),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], name=op.f('registration_requests_ibfk_2')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('registration_requests_ibfk_3')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('registration_requests_ibfk_4')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_registration_status_created'), ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_registration_email'), ['email'], unique=False)

    with op.batch_alter_table('emergency_cases', schema=None) as batch_op:
        batch_op.drop_index('idx_emergency_cases_status_severity')

    op.drop_table('emergency_cases')
    # ### end Alembic commands ###
