"""Initial migration

Revision ID: 5f4b6bc59798
Revises: 01d0fbd20b25
Create Date: 2026-08-12 22:34:47.662113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4b6bc59798'
down_revision = '01d0fbd20b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.Enum('cash', 'upi', 'card', name='appointment_payment_type'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
