"""Initial migration

Revision ID: b832b34434a7
Revises: 5f4b6bc59798
Create Date: 2026-08-13 12:39:30.010652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b832b34434a7'
down_revision = '5f4b6bc59798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nursing_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_case_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'emergency_cases', ['emergency_case_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nursing_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('emergency_case_id')

    # ### end Alembic commands ###
